# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourreferal',
            name='user',
        ),
        migrations.DeleteModel(
            name='YourReferal',
        ),
    ]
