# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0002_auto_20170912_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
