# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0004_auto_20170912_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField(max_length=200)),
            ],
        ),
    ]
