# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0005_auto_20171004_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal_id',
            field=models.IntegerField(),
        ),
    ]
