# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0006_auto_20171004_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
