# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0008_remove_profile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_id',
        ),
    ]
