# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0009_remove_profile_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
