# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0010_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourReferal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_no', models.CharField(max_length=20)),
            ],
        ),
    ]
