# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0011_auto_20171005_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referral_response',
            new_name='Referral',
        ),
    ]
