# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0012_auto_20171005_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
