# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0012_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.CharField(default='thjdg', max_length=30),
        ),
    ]
