# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0013_auto_20171006_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
