# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0013_profile_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral',
            field=models.CharField(max_length=30),
        ),
    ]
