# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0015_auto_20171009_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
