# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0016_profile_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
