# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0017_contact_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal_id',
            field=models.IntegerField(blank=True, default=1234567890, null=True),
        ),
    ]
