# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nhdo_main', '0018_auto_20171009_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='your_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
