# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0020_auto_20171009_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='your',
        ),
    ]
