# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0022_auto_20171026_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='your_referal',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='your_referal',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.DeleteModel(
            name='Your_referal',
        ),
    ]
