# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0023_auto_20171029_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
