# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0024_auto_20171029_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='count',
            new_name='count4',
        ),
        migrations.AddField(
            model_name='profile',
            name='count5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
