# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdo_main', '0025_auto_20171029_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level1',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
